name: ✨ Feature Request
description: Suggest a new feature or enhancement for OTTPRO
title: "[Feature]: "
labels: ["enhancement", "needs-triage"]
body:
  - type: markdown
    attributes:
      value: |
        Thanks for suggesting a new feature! Please provide as much detail as possible.

  - type: dropdown
    id: feature-type
    attributes:
      label: Feature Type
      description: What type of feature are you requesting?
      options:
        - New OTT Platform Support
        - Enhancement to Existing Feature
        - User Interface Improvement
        - Performance Optimization
        - Developer Experience
        - Other
    validations:
      required: true

  - type: input
    id: website-url
    attributes:
      label: Website URL
      description: URL where this feature would be used or demonstrated
      placeholder: https://example.com/page-where-feature-applies
    validations:
      required: false

  - type: textarea
    id: problem-statement
    attributes:
      label: Problem Statement
      description: What problem does this feature solve?
      placeholder: Describe the problem or limitation you're experiencing...
    validations:
      required: true

  - type: textarea
    id: proposed-solution
    attributes:
      label: Proposed Solution
      description: What would you like to see implemented?
      placeholder: Describe your proposed solution in detail...
    validations:
      required: true

  - type: textarea
    id: patch-description
    attributes:
      label: Patch Description
      description: Technical implementation details or code changes needed
      placeholder: |
        Describe the technical approach:
        - Files that need modification
        - New functions or components required
        - Integration points with existing code
        - Any dependencies or requirements
    validations:
      required: false

  - type: textarea
    id: screenshots-videos
    attributes:
      label: Screenshots or Videos
      description: Upload screenshots, mockups, or videos demonstrating the feature
      placeholder: |
        Drag and drop images/videos here or paste them directly.

        Visual examples help us understand your request better:
        - Screenshots of current state vs desired state
        - Mockups or wireframes of the proposed feature
        - Videos showing the expected behavior
        - Examples from other platforms or applications
